### PR TITLE
Update README.md - change repo name

### PR DESCRIPTION
**Pull request by gocadimic**

### CODE REVIEW

**Review by jpradocueva — CHANGES_REQUESTED** [review]
@gocadimic, the change on the name of the repository has a negative impact. The tables have disappeared. I was under the impression that it is not possible to change the name of the repository.

**Comment by gocadimic** [comment]
@jpradocueva, we can always return to the old repository's name

**Review by jpradocueva — COMMENTED** [review]
@gocadimic, line 67 needs to be updated by removing the word `dot`. Also the PR has conflcts, it cannot be merged.

**Review by jpradocueva — APPROVED** [review]
@gocadimic, thanks. I am merging the PR.

**Pull request merged**
